CREATE DATABASE HANGRONG
GO
USE HANGRONG
GO

CREATE TABLE THANHVIEN
    (
      [USER_ID] NVARCHAR(50) PRIMARY KEY,
      MatKhau NVARCHAR(100),
      TEN NVARCHAR(60) ,
      DIACHI NVARCHAR(60) ,
      SODIENTHOAI VARCHAR(30) ,
      NGAYTHAMGIA NVARCHAR(50) ,
      ANH NVARCHAR(100) ,
      CHUCNANG NVARCHAR(50)
    )
GO
CREATE TABLE MATHANG
    (
      MAMATHANG NVARCHAR(30) ,
      NGAYDANG NVARCHAR(100) ,
      MOTA NVARCHAR(30) ,
      LoaiHang NVARCHAR(100),
      TINHTRANG NVARCHAR(50),
      NGUOIBAN NVARCHAR(50) FOREIGN KEY REFERENCES THANHVIEN ([USER_ID])
      CONSTRAINT PK_MATHANG PRIMARY KEY ( MAMATHANG )
    )
GO
CREATE TABLE GIAODICH
(
	MaGiaoDich INT IDENTITY PRIMARY KEY,
	MAMATHANG NVARCHAR(30) FOREIGN KEY REFERENCES MATHANG (MAMATHANG),
	TGDatHang NVARCHAR(50),
	TGNhanHang NVARCHAR(50),
	NguoiBan NVARCHAR(50) FOREIGN KEY REFERENCES THANHVIEN ([USER_ID]),
	NguoiMua NVARCHAR(50) FOREIGN KEY REFERENCES THANHVIEN ([USER_ID])
)
